sudo: required
dist: trusty
language: node_js
node_js:
  - "6"
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta
env:
  - GOOGLE_CHROME_BINARY=/usr/bin/google-chrome-beta
before_install:
  - google-chrome-stable --headless --no-sandbox --disable-gpu --remote-debugging-port=9222 http://localhost:4444
